### ISSUE TITLE
[정보] Test를 어떻게 해볼까요?

### ISSUE THREAD

**Issue by ca1af** [ByeongDoo-Han/ToyProject-ShoppingMall#24]
# #23 해당 리뷰를 참고해주세요!

# 여러분의 의견 궁금합니다. 테스트를 어떤 방식으로 해 나갈지에 대해서 의견 부탁드려요! 댓글로 알려주세요.

**Comment by minseon33** [comment]
제 생각도 테스트코드를 먼저 작성하고 코드를 작성하는게 더 공부에 도움이 된다고 생각합니다.
1. 구현해야 할 기능을 먼저 생각한다.
2. 그 기능의 성공케이스들을 먼저 생각한다 (아직 코드를 구현하지 않았으니 에러가 날 것임) assertThat.isEquerse 블라블라
3. 성공케이스들을 먼저 구현한다.
4. 성공케이스들 이외에 발생할 수 있는 에러케이스들을 생각한다.
5. 에러케이스들에 대해서 예외처리를 구현한다. 

정도로 생각해봤습니다.
