### ISSUE TITLE
[정보] Refactor vs Fix  어떤 걸 써야할까?

### ISSUE THREAD

**Issue by ca1af** [ByeongDoo-Han/ToyProject-ShoppingMall#26]
# [레퍼런스 링크](https://zaraza.tistory.com/92#:~:text=%EC%95%9E%EC%9C%BC%EB%A1%9C%EB%8A%94%20refactor%20%ED%83%9C%EA%B7%B8%EB%8A%94%20%EC%82%AC%EC%9A%A9%EC%9E%90,fix%20%ED%83%9C%EA%B7%B8%EB%A5%BC%20%EC%82%AC%EC%9A%A9%ED%95%B4%EC%95%BC%EA%B2%A0%EB%8B%A4.)

위에서 보시는 바와 같이,

# 1. Fix

기능의 변경이 있을 때 사용합니다. 

# 2. Refactor

기능의 변경 없이, 아키텍쳐 혹은 구조의 변경이 있을 때 사용합니다.

**Comment by minseon33** [comment]
넵 확인했습니다~!

**Comment by ByeongDoo-Han** [comment]
확인했슴둥~!

**Comment by ca1af** [comment]
내리겠습니다!
